### ISSUE TITLE
Support for adding cameras not by IP but by SN (serial number)

### ISSUE THREAD

**Issue by MaCroX95** [flathub/net.meijn.onvifviewer#14]
How plausible is this to implement? Have there been any plans?

**Comment by caspermeijn** [comment]
ONVIFViewer requires a IP address to be able to connect to a camera. However there is an option for automatically discovering devices. This will show the name of devices in the network. When you click the name, it will add a camera and automatically fill in the IP. Will this solve your problem?

**Comment by MaCroX95** [comment]
> ONVIFViewer requires a IP address to be able to connect to a camera. However there is an option for automatically discovering devices. This will show the name of devices in the network. When you click the name, it will add a camera and automatically fill in the IP. Will this solve your problem?

Hey! Our IP Cam is connected to neighbor's Wifi, on my android device I can easily connect to it with serial number and username/password. I've been searching for software on linux that could do the same, this app is closest to it, but it only supports IP, and the problem is I don't know what the public IP of the camera is.

**Comment by caspermeijn** [comment]
I believe this functionality is already available in the app under `Add -> Automatically found camera`. This will list all ONVIF cameras found on the network.

**Comment by MaCroX95** [comment]
> I believe this functionality is already available in the app under `Add -> Automatically found camera`. This will list all ONVIF cameras found on the network.

Actually, the point of having the option to connect to SN directly is that the camera doesn't have to be connected to your local router, which is quite common in places where you have multiple wifi networks.

On Android, many apps support the option of adding them by SN and also on Windows proprietary program. 

I have no idea though which protocol is being used for connection and whether the devices have unique identifiers across all manufacturers.

**Comment by caspermeijn** [comment]
Now I understand what you mean. Sadly that is not part of the ONVIF standard, this is probably specific to your camera.

**Comment by ShubhamKPBoss** [comment]
Hello, can you please help me how to connect ip camera using camera --> serial number ,port , username, password
which type of following protocol  ....... ?

**Comment by caspermeijn** [comment]
Unfortunately, ONVIFViewer doesn't support connecting by serial number.  Let me know if you are willing to sponsor this feature (either through money or code).
