### ISSUE TITLE
No icons appear

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/net.meijn.onvifviewer#2]
![captura de tela de 2018-08-27 08-36-10](https://user-images.githubusercontent.com/26097419/44657879-dc5c5680-a9d4-11e8-9008-33a8bba689df.png)
![captura de tela de 2018-08-27 08-40-13](https://user-images.githubusercontent.com/26097419/44657878-dbc3c000-a9d4-11e8-9704-046c44116c66.png)

**Comment by caspermeijn** [comment]
Hi @LeandroStanger, sorry for the late reaction. This is an icon that is loaded from the theme. So appearantly youre theme doesn't have the icon transform-move. Could you check that the icon is not on your system using the following command? `find /usr/share/icons/ -name transform-move.*`

**Comment by LeandroStanger** [comment]
![captura de tela de 2018-09-10 17-07-39](https://user-images.githubusercontent.com/26097419/45321566-0b69e080-b51c-11e8-89bd-8dcb3b8be88f.png)

**Comment by caspermeijn** [comment]
The action icon `transform-move` is not available in the users icon theme. However it is in the breeze icon theme (which is available in the runtime). I don't want to force the breeze theme, as then the application would not integrate well. @TingPing What is the best solution here? Or could you point me to the best place to ask this question?

**Comment by LeandroStanger** [comment]
@bilelmoussaoui could you help?

**Comment by bilelmoussaoui** [comment]
@caspermeijn The only possible solution here is to either force breeze theme or add those icons as resource https://lazka.github.io/pgi-docs/Gtk-3.0/classes/IconTheme.html#Gtk.IconTheme.add_resource_path
https://valadoc.org/gtk+-3.0/Gtk.IconTheme.add_resource_path.html
And bundles the icons within the application itself.

**Comment by LeandroStanger** [comment]
@caspermeijn How is the progress of the correction going?

**Comment by caspermeijn** [comment]
Thanks for reminding me. I was able to reproduce this problem. I think that [QIcon::setFallbackThemeName()](https://doc-snapshots.qt.io/qt5-dev/qicon.html#setFallbackThemeName) can be a solution to this problem. But this requires Qt 5.12 so it could take a little time.

**Comment by LeandroStanger** [comment]
![captura de tela de 2018-11-21 17-58-24](https://user-images.githubusercontent.com/26097419/48865563-1d3af000-edb7-11e8-80e0-fc456aabcc6a.png)

![captura de tela de 2018-11-21 17-58-30](https://user-images.githubusercontent.com/26097419/48865559-1c09c300-edb7-11e8-97ee-939a08645de7.png)

**Comment by caspermeijn** [comment]
Great to see this be resolved!
